function loadLocal() {
  const listcar = [
    {
      sldb: 0,
      idcar: "GoDs",
      namecar: "A4 Sedan Advanced",
      slx: 1,
      pricecar: "1990000000",
      seriescar: "A Series",
      img1car: "../xe/A4sedan.png",
      img2car: "../xe/a4sedan-2.png",
      img1: "../color/a4 (1).png",
      img2: "../color/a4 (3).png",
      img3: "../color/a4 (4).png",
      img4: "../color/a4 (2).png",
      img5: "../color/a4 (6).png",
      img6: "../color/a4 (5).png",
      namecolor1: "1",
      namecolor2: "3",
      namecolor3: "4",
      namecolor4: "5",
      namecolor5: "6",
      namecolor6: "2",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "QMTv",
      namecar: "A6 TFSI 45",
      slx: 5,
      pricecar: "2300000000",
      seriescar: "A Series",
      img1car: "../xe/A6.png",
      img2car: "../xe/a6-2.png",
      img1: "../color/a6 (1).png",
      img2: "../color/a6 (2).png",
      img3: "../color/a6 (3).png",
      img4: "../color/a6 (4).png",
      img5: "../color/a6 (5).png",
      img6: "../color/a6 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "63nH",
      namecar: "A7 Sportback",
      slx: 27,
      pricecar: "3700000000",
      seriescar: "A Series",
      img1car: "../xe/a7.png",
      img2car: "../xe/a7-sb.png",
      img1: "../color/a7 (1).png",
      img2: "../color/a7 (2).png",
      img3: "../color/a7 (3).png",
      img4: "../color/a7 (4).png",
      img5: "../color/a7 (5).png",
      img6: "../color/a7 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "FRqW",
      namecar: "A8 L",
      slx: 16,
      pricecar: "3800000000",
      seriescar: "A Series",
      img1car: "../xe/a8l.png",
      img2car: "../xe/a8l-2.png",
      img1: "../color/a8 (1).png",
      img2: "../color/a8 (2).png",
      img3: "../color/a8 (4).png",
      img4: "../color/a8 (3).png",
      img5: "../color/a8 (5).png",
      img6: "../color/a8 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "7ndd",
      namecar: "e-tron",
      slx: 8,
      pricecar: "3200000000",
      seriescar: "e-tron Series",
      img1car: "../xe/etron.png",
      img2car: "../xe/etron-2.png",
      img1: "../color/et (1).png",
      img2: "../color/et (2).png",
      img3: "../color/et (3).png",
      img4: "../color/et (4).png",
      img5: "../color/et (5).png",
      img6: "../color/et (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "Ty0Y",
      namecar: "e-tron GT",
      slx: 11,
      pricecar: "5300000000",
      seriescar: "e-tron Series",
      img1car: "../xe/etrongt.png",
      img2car: "../xe/etrongt-2.png",
      img1: "../color/etgt (1).png",
      img2: "../color/etgt (2).png",
      img3: "../color/etgt (3).png",
      img4: "../color/etgt (4).png",
      img5: "../color/etgt (5).png",
      img6: "../color/etgt (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "3Usq",
      namecar: "RS e-tron GT",
      slx: 2,
      pricecar: "6800000000",
      seriescar: "e-tron Series",
      img1car: "../xe/RS.png",
      img2car: "../xe/RS-2.png",
      img1: "../color/rs (1).png",
      img2: "../color/rs (2).png",
      img3: "../color/rs (3).png",
      img4: "../color/rs (4).png",
      img5: "../color/rs (5).png",
      img6: "../color/rs (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "M64V",
      namecar: "Q2",
      slx: 11,
      pricecar: "2300000000",
      seriescar: "Q Series",
      img1car: "../xe/q2.png",
      img2car: "../xe/q2-2.png",
      img1: "../color/q2 (1).png",
      img2: "../color/q2 (2).png",
      img3: "../color/q2 (3).png",
      img4: "../color/q2 (4).png",
      img5: "../color/q2 (5).png",
      img6: "../color/q2 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "8O6S",
      namecar: "Q3",
      slx: 22,
      pricecar: "3800000000",
      seriescar: "Q Series",
      img1car: "../xe/q3.png",
      img2car: "../xe/q3-2.png",
      img1: "../color/q3 (1).png",
      img2: "../color/q3 (2).png",
      img3: "../color/q3 (3).png",
      img4: "../color/q3 (4).png",
      img5: "../color/q3 (5).png",
      img6: "../color/q3 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "vdmO",
      namecar: "Q3 Sportback",
      slx: 14,
      pricecar: "4200000000",
      seriescar: "Q Series",
      img1car: "../xe/q3.png",
      img2car: "../xe/q5-sb.png",
      img1: "../color/q3sb (1).png",
      img2: "../color/q3sb (2).png",
      img3: "../color/q3sb (3).png",
      img4: "../color/q3sb (4).png",
      img5: "../color/q3sb (5).png",
      img6: "../color/q3sb (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "w9YH",
      namecar: "Q5",
      slx: 32,
      pricecar: "5200000000",
      seriescar: "Q Series",
      img1car: "../xe/q5.png",
      img2car: "../xe/q5-2.png",
      img1: "../color/q5 (1).png",
      img2: "../color/q5 (2).png",
      img3: "../color/q5 (3).png",
      img4: "../color/q5 (4).png",
      img5: "../color/q5 (5).png",
      img6: "../color/q5 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "xqr4",
      namecar: "Q5 Sportback",
      slx: 11,
      pricecar: "4900000000",
      seriescar: "Q Series",
      img1car: "../xe/q5.png",
      img2car: "../xe/q5-sb.png",
      img1: "../color/q5sb (1).png",
      img2: "../color/q5sb (2).png",
      img3: "../color/q5sb (3).png",
      img4: "../color/q5sb (4).png",
      img5: "../color/q5sb (5).png",
      img6: "../color/q5sb (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "SsRR",
      namecar: "Q7",
      slx: 17,
      pricecar: "7500000000",
      seriescar: "Q Series",
      img1car: "../xe/q7.png",
      img2car: "../xe/q7-2.png",
      img1: "../color/q7 (1).png",
      img2: "../color/q7 (2).png",
      img3: "../color/q7 (3).png",
      img4: "../color/q7 (4).png",
      img5: "../color/q7 (5).png",
      img6: "../color/q7 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
    {
      sldb: 0,
      idcar: "hvye",
      namecar: "Q8",
      slx: 12,
      pricecar: "7300000000",
      seriescar: "Q Series",
      img1car: "../xe/q8.png",
      img2car: "../xe/q8-2.png",
      img1: "../color/q8 (1).png",
      img2: "../color/q8 (2).png",
      img3: "../color/q8 (3).png",
      img4: "../color/q8 (4).png",
      img5: "../color/q8 (5).png",
      img6: "../color/q8 (6).png",
      namecolor1: "1",
      namecolor2: "2",
      namecolor3: "3",
      namecolor4: "4",
      namecolor5: "5",
      namecolor6: "6",
      nametag1: "",
      nametag2: "",
      nametag3: "",
      nametag4: "",
      nametag5: "",
      nametag6: "",
    },
  ];
  if (JSON.parse(localStorage.getItem("listcar")) === null) {
    localStorage.setItem("listcar", JSON.stringify(listcar));
  }
  const account = [
    {
      name: "Lê Nguyễn Đức Anh",
      email: "anhaudi88@gmail.com",
      avtSrc: "../audi/avt/admin.jpg",
      ngaysinh: "2003-07-07",
      chucvu: "quanly",
      user: "admin",
      pass: "ducanhne",
      index: 0,
      id: "~!QP4W",
      tttk: '<i class="ri-checkbox-circle-fill" style="color: green"></i>',
    },
  ];
  if (JSON.parse(localStorage.getItem("accounts")) === null) {
    localStorage.setItem("accounts", JSON.stringify(account));
  }
  const listnv = [
    {
      idnv: "fnW",
      namenv: "Lê Nguyễn Đức Anh",
      bornnv: "2003-07-07",
      chucvunv: "Quản lý",
      phongbannv: "Điều hành",
      emailnv: "anhaudi88@gmail.com",
      sdtnv: "0123456789",
      anhnv: "../audi/avt/z4079128930272_5831c10d6580c78c38c544ad3ba7884e.jpg",
    },
  ];
  if (JSON.parse(localStorage.getItem("listNV")) === null) {
    localStorage.setItem("listNV", JSON.stringify(listnv));
  }
}
